#include "incl_resid.h"

#include STR(LOCAL_SKETCH_DIR/reSID16/envelope.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/extfilt.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/filter.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/pot.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/version.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/voice.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/wave6581__ST.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/wave6581_P_T.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/wave6581_PS_.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/wave6581_PST.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/wave8580__ST.cc) 
#include STR(LOCAL_SKETCH_DIR/reSID16/wave8580_P_T.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/wave8580_PS_.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/wave8580_PST.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/wave.cc)
#include STR(LOCAL_SKETCH_DIR/reSID16/sid.cc)

#include STR(LOCAL_SKETCH_DIR/reSID/envelope.cc)
#include STR(LOCAL_SKETCH_DIR/reSID/extfilt.cc)
#include STR(LOCAL_SKETCH_DIR/reSID/filter.cc)
#include STR(LOCAL_SKETCH_DIR/reSID/version.cc)
#include STR(LOCAL_SKETCH_DIR/reSID/voice.cc)
#include STR(LOCAL_SKETCH_DIR/reSID/dac.cc)
#include STR(LOCAL_SKETCH_DIR/reSID/wave.cc)
#include STR(LOCAL_SKETCH_DIR/reSID/sid.cc)
